### ISSUE TITLE
feature request: Make standalone pods deletebale

### ISSUE THREAD

**Issue by erkules** [falcosecurity/falco-talon#451]
Hi,

If you try to kill a standalone  pod (kubernetes:terminate) Falco-Talon skips/errors with `"no owner reference found"` 
So you will never be able to kill "standalone" Pods. 
So a good way to attack would be a "standalone" Pods. On the other hand there are Operators like pgng? being a controller for the pods themself not using sts, deploy etc.

**Comment by IgorEulalio** [comment]
Hello @erkules. 

We're working on that, it should be available in the next release 0.2.0.

**Comment by Issif** [comment]
The feature is now available in the [v0.2.0](https://github.com/falcosecurity/falco-talon/releases/tag/v0.2.0
