### ISSUE TITLE
official helm chart

### ISSUE THREAD

**Issue by UgniusV** [falcosecurity/falco-talon#471]
Hey team, do you have any ETAs on when the official helm chart will be released for falco-talon? Currently there is only an [unofficial version](https://artifacthub.io/packages/helm/portefaix-hub/falco-talon).

**Comment by Issif** [comment]
Hi,

We recently got the [votes from the Falco community to integrate Talon in the official organization](https://github.com/falcosecurity/evolution/issues/403). It means I'll transfer the ownership this week, and at the same time, it will move the helm template into the official [charts repo](https://github.com/falcosecurity/charts) to get the benefit of the CI and allow Talon's chart to be aside the others.
